Implemented method for grabbing objects
abbindustrigymnasium/VRregVast pull request #26
Opened 2024-04-17 07:55 UTC by Abb22TedStr

A new scene (Grabbing) where you can grab objects.

2024-04-23 11:21 UTC, abbolisar approved these changes
Merged 🆎

2024-04-23 11:23 UTC, Abb22TedStr reviewed
Wait with giving approval until Hampus merges his branch (highlighting objects) with this!

2024-04-23 16:45 UTC, Hampus220S commented
I am now done implementing the ability to highlight objects that the user can grab. The program only highlights the closest grab-able object (the one you will grab), but for some unknown reason, the hand doesn't always grab the closest object. That will have to be investigated at some point, but not now :)

How to make objects have the ability to be interact-able, and get an outline, is partly documented in the newly created markdown file called IntegrationInstructions.

2024-04-23 16:53 UTC, Hampus220S commented
When this pull request gets closed, also close this issue with the same content:
#7

2024-04-24 06:36 UTC, tramvaj99 requested changes

2024-04-24 06:36 UTC, tramvaj99 commented on VR_RV/Assets/Scenes/Gameplay Scenes/Bare Bones/Scripts/OutlineReceiver.cs
> +  void onDestory()
```suggestion
  void onDestroy()
```

Should this be onDestroy?

2024-04-24 06:38 UTC, Hampus220S commented on VR_RV/Assets/Scenes/Gameplay Scenes/Bare Bones/Scripts/OutlineReceiver.cs
> +  void onDestory()
Maybe... :)

2024-04-24 06:48 UTC, abbsimmei approved these changes
I approve!

2024-04-24 06:48 UTC, abbsimmei approved these changes
I approve again

2024-04-24 06:49 UTC, merged