Added Oculus hand models and basic animations
abbindustrigymnasium/VRregVast pull request #27
Opened 2024-04-17 08:27 UTC by ABB22OllOst

Removed the spheres and replaced them with animated hands

2024-04-23 10:33 UTC, tramvaj99 requested changes
Please rename the folders so that they match the guidelines in FileGuidlines.md

2024-04-23 11:55 UTC, abbolisar approved these changes
🆎

2024-04-24 10:29 UTC, ABB22OllOst commented
> Händerna ser jättebra ut!! Tyvärr fryser de ibland, rätt så ofta, vilket får det att verka rätt buggigt. Går det att lösa?
> 
> Det buggade både på Quest 2 och 3.

Det är inget jag kan fixa och de hära är bara placeholders innan vi gör några egna.

2024-04-30 11:43 UTC, tramvaj99 approved these changes
Bra att du löste, ser super ut Olle!

2024-04-30 12:20 UTC, merged