Added other way to test vr in README.md
abbindustrigymnasium/VRregVast pull request #33
Opened 2024-04-17 09:06 UTC by abbgavger

2024-04-17 09:06 UTC, ABB22denfor approved these changes

2024-04-23 10:24 UTC, tramvaj99 requested changes
Hittade ett litet stavfel, annars ser det bra ut!

2024-04-23 10:24 UTC, tramvaj99 commented on README.md
> +Go to **Build Settings** -> **Player Settings** -> **OpenXR**, go to the Computer tab. In Enabled Interaction Profiles add **Valve Index Controller Profile** Start the Oculus App, make sure to update
```suggestion
Go to **Build Settings** -> **Player Settings** -> **OpenXR**, go to the Computer tab. In Enabled Interaction Profiles add **Valve Index Controller Profile** Start the Oculus App, make sure to update drivers. **Go to Settings** -> **General**, make sure that the **Unknown Sources** option is enabled. Allow all pop ups that come up in the Headset. Go to Quest Link then press launch. Press the button with the computer screen in the dock on the bottom of the screen. Press play in Unity.
```

2024-04-23 11:05 UTC, abbolisar approved these changes
kool

2024-04-23 11:05 UTC, merged