Added 3D-models for various tools and colliders for said models
abbindustrigymnasium/VRregVast pull request #44
Opened 2024-04-30 13:11 UTC by Abb22TedStr

2024-04-30 13:57 UTC, tramvaj99 requested changes
- [x] Could you add a collider to the floor of the room? Right now object fall through.
- [ ] The floor is too high, should always be below the player. 
- [ ] Is there a way to make the tools sit at the bottom of the basket instead of sitting on top of it?

2024-05-08 12:05 UTC, Abb22TedStr commented
Ska merge:a Olles händer och se om Hampus gjorde ändringar till outlinen nästa vecka.

2024-05-17 11:06 UTC, Abb-FilGal requested changes
Change sax to scissor to comply with our choice to keep everything in english

2024-05-17 11:58 UTC, Abb-FilGal approved these changes

2024-05-17 12:00 UTC, tramvaj99 reviewed
See comment on OutlineCreator.

2024-05-17 12:00 UTC, tramvaj99 commented on VR_RV/Assets/Scenes/Gameplay Scenes/Bare Bones/Scripts/OutlineCreator.cs
This seems to be the old, unoptimized code for the outlinecreator. See now merged PR #41 for the optimized code.

2024-05-17 12:47 UTC, Abb22TedStr commented on VR_RV/Assets/Scenes/Gameplay Scenes/Bare Bones/Scripts/OutlineCreator.cs
It seems my Visual Studio Code has trouble fetching the latest master branch from GitHub, so there might be more old code that I'm unaware of, sadly. I think this was the only file that wasn't up to date, however, and I've just copy-pasted the latest code from GitHub into my Visual Studio Code and commited it.

2024-05-21 10:17 UTC, abbolisar approved these changes
fint

2024-05-21 10:17 UTC, merged