Added disinfection system
abbindustrigymnasium/VRregVast pull request #68
Opened 2024-05-24 06:42 UTC by lucasAxberg

Added system for calculating the disinfected area + system for higlighting the disinfected area

2024-05-24 09:02 UTC, tramvaj99 requested changes
Looks great, I just acted as spellcheck for some comments.

2024-05-24 09:02 UTC, tramvaj99 commented on VR_RV/Assets/Scenes/Gameplay Scenes/Gameplay Scene 4/Scripts/MeshPaint.cs
> +        // Printing x and y coodrinates
```suggestion
        // Printing x and y coordinates
```

2024-05-24 09:02 UTC, tramvaj99 commented on VR_RV/Assets/Scenes/Gameplay Scenes/Gameplay Scene 4/Scripts/MeshPaint.cs
> +        // If the sum of angles are PI (with a margin of 0.01), return true
```suggestion
        // If the sum of angles is PI (with a margin of 0.01), return true
```

2024-05-24 09:02 UTC, tramvaj99 commented on VR_RV/Assets/Scenes/Gameplay Scenes/Gameplay Scene 4/Scripts/MeshPaint.cs
> +        // Loops through all the collision vertecies
```suggestion
        // Loops through all the collision vertices
```

2024-05-26 18:40 UTC, tramvaj99 approved these changes
Great!

2024-05-27 05:37 UTC, abbolisar approved these changes
**a**

2024-05-27 05:37 UTC, merged